<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "outdatedcontentfinder"
 *
 * Auto generated by Extension Builder 2015-03-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Outdated Pages Finder',
    'description' => 'Displays possibly outdated pages and content that the user has edit access for',
    'category' => 'module',
    'author' => 'Lorenz Ulrich',
    'author_email' => 'lorenz.ulrich@visol.ch',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-7.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
